version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: dependencies
          command: |
            yarn
            yarn truffle install
      - run:
          name: test
          command: yarn test:all